# This workflow will upload a Python Package as a GitHub release

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy to various OSes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install PyQt6 pyinstaller
    - name: Build and publish
      run: |
        pyinstaller Ninja_preview.spec
        python uploader.py ${{ matrix.os }} ${{ secrets.ACCESS_TOKEN }}
